#ifndef MY_OPTIONS_H
#define MY_OPTIONS_H

#define MAX_NODE_SIZE 30
#define MAX_NUM_NODES 30

#define MAX_FORMULA_LEN 250

#define MAX_COMMAND_LEN 256+MAX_FORMULA_LEN

#define DEFAULT_MEASURE_EXE MEASURE_LOC

#define MAX_MUTATION_TRIES 10

#define HASH_SIZE 32749

#endif
